/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fazer login */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/check-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verificar se usuário existe */
        post: operations["checkUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/change-pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Alterar PIN do usuário */
        post: operations["changePin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partituras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar partituras */
        get: operations["getPartituras"];
        put?: never;
        /** Criar partitura (admin) */
        post: operations["createPartitura"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partituras/upload-pasta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload de pasta com múltiplas partes (admin) */
        post: operations["uploadPastaPartitura"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partituras/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter partitura por ID */
        get: operations["getPartitura"];
        /** Atualizar partitura (admin) */
        put: operations["updatePartitura"];
        post?: never;
        /** Deletar partitura (admin) */
        delete: operations["deletePartitura"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partituras/{id}/partes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar partes de uma partitura */
        get: operations["getPartesPartitura"];
        put?: never;
        /** Adicionar parte a uma partitura (admin) */
        post: operations["addParte"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partes/{id}/substituir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Substituir arquivo de uma parte (admin) */
        put: operations["substituirParte"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Deletar parte (admin) */
        delete: operations["deleteParte"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/download/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download da partitura completa */
        get: operations["downloadPartitura"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/download/parte/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download de uma parte específica */
        get: operations["downloadParte"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categorias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar categorias */
        get: operations["getCategorias"];
        put?: never;
        /** Criar categoria (admin) */
        post: operations["createCategoria"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categorias/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Atualizar categoria (admin) */
        put: operations["updateCategoria"];
        post?: never;
        /** Deletar categoria (admin) */
        delete: operations["deleteCategoria"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categorias/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reordenar categorias (admin) */
        post: operations["reorderCategorias"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favoritos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar favoritos do usuário */
        get: operations["getFavoritos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favoritos/ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter IDs dos favoritos */
        get: operations["getFavoritosIds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favoritos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adicionar partitura aos favoritos */
        post: operations["addFavorito"];
        /** Remover partitura dos favoritos */
        delete: operations["removeFavorito"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atividades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar atividades recentes */
        get: operations["getAtividades"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/minhas-atividades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar atividades do usuário logado */
        get: operations["getAtividadesUsuario"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/estatisticas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter estatísticas públicas */
        get: operations["getEstatisticas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instrumentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar instrumentos disponíveis */
        get: operations["getInstrumentos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/estatisticas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter estatísticas administrativas */
        get: operations["getEstatisticasAdmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar usuários (admin) */
        get: operations["getUsuarios"];
        put?: never;
        /** Criar usuário (admin) */
        post: operations["createUsuario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usuarios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter usuário por ID (admin) */
        get: operations["getUsuario"];
        /** Atualizar usuário (admin) */
        put: operations["updateUsuario"];
        post?: never;
        /** Deletar usuário (admin) */
        delete: operations["deleteUsuario"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/perfil": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter perfil do usuário logado */
        get: operations["getPerfil"];
        /** Atualizar perfil */
        put: operations["updatePerfil"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/perfil/foto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload de foto de perfil */
        post: operations["uploadFotoPerfil"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repertorio/ativo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter repertório ativo */
        get: operations["getRepertorioAtivo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repertorio/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter repertório por ID */
        get: operations["getRepertorio"];
        /** Atualizar repertório (admin) */
        put: operations["updateRepertorio"];
        post?: never;
        /** Deletar repertório (admin) */
        delete: operations["deleteRepertorio"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repertorio/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download do repertório (ZIP) */
        get: operations["downloadRepertorio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repertorio/{id}/instrumentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar instrumentos disponíveis no repertório */
        get: operations["getRepertorioInstrumentos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partituras/{id}/in-repertorio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verificar se partitura está no repertório ativo */
        get: operations["isPartituraInRepertorioAtivo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repertorios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar todos os repertórios (admin) */
        get: operations["listRepertorios"];
        put?: never;
        /** Criar repertório (admin) */
        post: operations["createRepertorio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repertorio/{id}/partituras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adicionar partitura ao repertório (admin) */
        post: operations["addPartituraToRepertorio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repertorio/{repertorioId}/partituras/{partituraId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remover partitura do repertório (admin) */
        delete: operations["removePartituraFromRepertorio"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repertorio/{id}/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reordenar partituras no repertório (admin) */
        put: operations["reorderPartiturasRepertorio"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repertorio/{id}/duplicar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Duplicar repertório (admin) */
        post: operations["duplicarRepertorio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        Success: {
            success?: boolean;
            message?: string;
        };
        LoginRequest: {
            username: string;
            pin: string;
        };
        LoginResponse: {
            token?: string;
            user?: components["schemas"]["User"];
        };
        CheckUserRequest: {
            username: string;
        };
        ChangePinRequest: {
            pin_atual: string;
            pin_novo: string;
        };
        User: {
            id?: number;
            username?: string;
            nome?: string;
            instrumento?: string;
            is_admin?: number;
            foto_url?: string | null;
            /** Format: date-time */
            criado_em?: string;
        };
        UserCreate: {
            username: string;
            nome: string;
            instrumento: string;
            pin: string;
            is_admin?: number;
        };
        UserUpdate: {
            nome?: string;
            instrumento?: string;
            is_admin?: number;
        };
        Categoria: {
            id?: number;
            nome?: string;
            emoji?: string;
            cor?: string;
            ordem?: number;
        };
        CategoriaCreate: {
            nome: string;
            emoji?: string;
            cor?: string;
        };
        CategoriaReorder: {
            ordem?: number[];
        };
        Partitura: {
            id?: number;
            titulo?: string;
            compositor?: string;
            arranjador?: string | null;
            categoria_id?: number;
            categoria_nome?: string;
            categoria_emoji?: string;
            categoria_cor?: string;
            ano?: number | null;
            descricao?: string | null;
            arquivo_nome?: string;
            arquivo_tamanho?: number;
            destaque?: number;
            total_partes?: number;
            /** Format: date-time */
            criado_em?: string;
        };
        PartituraUpdate: {
            titulo?: string;
            compositor?: string;
            arranjador?: string;
            categoria_id?: number;
            ano?: number;
            descricao?: string;
            destaque?: number;
        };
        Parte: {
            id?: number;
            partitura_id?: number;
            instrumento?: string;
            arquivo_nome?: string;
        };
        Favorito: {
            id?: number;
            partitura_id?: number;
            titulo?: string;
            compositor?: string;
        };
        FavoritosIds: {
            ids?: number[];
        };
        Atividade: {
            id?: number;
            tipo?: string;
            titulo?: string;
            subtitulo?: string;
            usuario_id?: number;
            usuario_nome?: string;
            /** Format: date-time */
            criado_em?: string;
        };
        Estatisticas: {
            total_partituras?: number;
            total_usuarios?: number;
            total_downloads?: number;
            total_categorias?: number;
        };
        EstatisticasAdmin: {
            total_partituras?: number;
            total_usuarios?: number;
            total_downloads?: number;
            downloads_mes?: number;
            usuarios_ativos?: number;
        };
        Instrumento: {
            instrumento?: string;
            total?: number;
        };
        Repertorio: {
            id?: number;
            nome?: string;
            descricao?: string | null;
            ativo?: number;
            /** Format: date-time */
            criado_em?: string;
            partituras?: components["schemas"]["Partitura"][];
        };
        RepertorioCreate: {
            nome: string;
            descricao?: string;
        };
        RepertorioUpdate: {
            nome?: string;
            descricao?: string;
            ativo?: number;
        };
        RepertorioInstrumento: {
            instrumento?: string;
            total?: number;
        };
        AddPartituraToRepertorio: {
            partitura_id: number;
        };
        ReorderPartituras: {
            ordem?: number[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API está funcionando */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                    };
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login bem-sucedido */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Credenciais inválidas */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    checkUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckUserRequest"];
            };
        };
        responses: {
            /** @description Usuário encontrado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        exists?: boolean;
                        nome?: string;
                    };
                };
            };
        };
    };
    changePin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePinRequest"];
            };
        };
        responses: {
            /** @description PIN alterado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
            /** @description PIN atual incorreto */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPartituras: {
        parameters: {
            query?: {
                /** @description Filtrar por categoria */
                categoria?: number;
                /** @description Buscar por título ou compositor */
                busca?: string;
                /** @description Apenas partituras em destaque */
                destaque?: "1";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de partituras */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Partitura"][];
                };
            };
        };
    };
    createPartitura: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    titulo: string;
                    compositor: string;
                    arranjador?: string;
                    categoria: number;
                    ano?: number;
                    descricao?: string;
                    /** @enum {string} */
                    destaque?: "0" | "1";
                    /** Format: binary */
                    arquivo: string;
                };
            };
        };
        responses: {
            /** @description Partitura criada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        id?: number;
                        message?: string;
                    };
                };
            };
            /** @description Partitura duplicada */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    uploadPastaPartitura: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    titulo: string;
                    compositor?: string;
                    arranjador?: string;
                    categoria: number;
                    ano?: number;
                    total_arquivos: number;
                };
            };
        };
        responses: {
            /** @description Partitura criada com partes */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        id?: number;
                        partes_criadas?: number;
                        message?: string;
                    };
                };
            };
        };
    };
    getPartitura: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Partitura encontrada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Partitura"];
                };
            };
            /** @description Partitura não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updatePartitura: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartituraUpdate"];
            };
        };
        responses: {
            /** @description Partitura atualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    deletePartitura: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Partitura removida */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    getPartesPartitura: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de partes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Parte"][];
                };
            };
        };
    };
    addParte: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    instrumento: string;
                    /** Format: binary */
                    arquivo: string;
                };
            };
        };
        responses: {
            /** @description Parte adicionada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    substituirParte: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID da parte (não da partitura) */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    arquivo: string;
                };
            };
        };
        responses: {
            /** @description Parte substituída */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    deleteParte: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID da parte (não da partitura) */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Parte removida */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    downloadPartitura: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Arquivo PDF */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            /** @description Arquivo não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    downloadParte: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Arquivo PDF */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
        };
    };
    getCategorias: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de categorias */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Categoria"][];
                };
            };
        };
    };
    createCategoria: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoriaCreate"];
            };
        };
        responses: {
            /** @description Categoria criada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    updateCategoria: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoriaCreate"];
            };
        };
        responses: {
            /** @description Categoria atualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    deleteCategoria: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categoria removida */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    reorderCategorias: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoriaReorder"];
            };
        };
        responses: {
            /** @description Categorias reordenadas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    getFavoritos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de favoritos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Favorito"][];
                };
            };
        };
    };
    getFavoritosIds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de IDs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoritosIds"];
                };
            };
        };
    };
    addFavorito: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID da partitura */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Favorito adicionado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    removeFavorito: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID da partitura */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Favorito removido */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    getAtividades: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de atividades */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Atividade"][];
                };
            };
        };
    };
    getAtividadesUsuario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de atividades do usuário */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Atividade"][];
                };
            };
        };
    };
    getEstatisticas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estatísticas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Estatisticas"];
                };
            };
        };
    };
    getInstrumentos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de instrumentos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instrumento"][];
                };
            };
        };
    };
    getEstatisticasAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estatísticas admin */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstatisticasAdmin"];
                };
            };
        };
    };
    getUsuarios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de usuários */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    createUsuario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Usuário criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    getUsuario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuário encontrado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    updateUsuario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Usuário atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    deleteUsuario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuário removido */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    getPerfil: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Perfil do usuário */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    updatePerfil: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    nome?: string;
                    instrumento?: string;
                };
            };
        };
        responses: {
            /** @description Perfil atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    uploadFotoPerfil: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    foto: string;
                };
            };
        };
        responses: {
            /** @description Foto atualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        foto_url?: string;
                    };
                };
            };
        };
    };
    getRepertorioAtivo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repertório ativo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repertorio"];
                };
            };
            /** @description Nenhum repertório ativo */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getRepertorio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repertório */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repertorio"];
                };
            };
        };
    };
    updateRepertorio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepertorioUpdate"];
            };
        };
        responses: {
            /** @description Repertório atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    deleteRepertorio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repertório removido */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    downloadRepertorio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Arquivo ZIP */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": string;
                };
            };
        };
    };
    getRepertorioInstrumentos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de instrumentos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepertorioInstrumento"][];
                };
            };
        };
    };
    isPartituraInRepertorioAtivo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        in_repertorio?: boolean;
                    };
                };
            };
        };
    };
    listRepertorios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de repertórios */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repertorio"][];
                };
            };
        };
    };
    createRepertorio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepertorioCreate"];
            };
        };
        responses: {
            /** @description Repertório criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    addPartituraToRepertorio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddPartituraToRepertorio"];
            };
        };
        responses: {
            /** @description Partitura adicionada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    removePartituraFromRepertorio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repertorioId: number;
                partituraId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Partitura removida */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    reorderPartiturasRepertorio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderPartituras"];
            };
        };
        responses: {
            /** @description Partituras reordenadas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    duplicarRepertorio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repertório duplicado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        id?: number;
                        message?: string;
                    };
                };
            };
        };
    };
}
